project:
  type: website
  output-dir: docs

website:
  title: "Mona Farnisa"
  site-url: https://monafarnisa.github.io/

  google-analytics:
    tracking-id: "G-G-W9WW2GESRZ"
    anonymize-ip: true

  navbar: 
    search: true
    left: 
      - href: index.qmd
        text: home
      #- include new quarto pages here  
      - href: about.qmd
        text: about me
      - href: projects.qmd
        text: projects
    right: 
      - icon: github
        href: https://github.com/dvirlar2
      - icon: linkedin
        href: https://www.linkedin.com/in/monafarnisa/
  
  page-footer:
    background: light # or dark
    left: Copyright 2023, Mona Farnisa
    right: This website is built with {{< fa github title="GitHub" >}}, {{< fa brands r-project title="R Project" >}} and [Quarto](https://quarto.org/).


format:
  html:
    theme: 
      light: darkly
      dark: darkly
    css: styles.css
    toc: true
    page-layout: full

editor: visual

