project:
  type: website
  output-dir: docs

website:
  title: "Mona Farnisa"
  navbar:
    left:
      - href: index.qmd
        text: home
      #- include new quarto pages here  
      #- about.qmd
      - projects.qmd

format:
  html:
    theme: 
      light: darkly
      dark: darkly
    css: styles.css
    toc: true
    page-layout: full

editor: visual

